kind: PersistentVolume
apiVersion: v1
metadata:
      name: pv-volume
      labels:
           type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    -  ReadWriteOnce
  hostPath:
    path: "/mydata"
