apiVersion: v1
kind: Pod
metadata:
     name: initcontainer
spec:
   initContainers:
          - name: sleepy
            image: alpine
            command: ['sleep','20']
   containers:
          - name: web
            image: nginx
