apiVersion: apps/v1
kind: Deployment
metadata:
        name: rolling-upates
        labels:
            app: nginx
spec:
   replicas: 4
   strategy:
       type: RollingUpdate
       rollingUpdate:
         maxSurge: 2
         maxUnavailable: 1
   selector:
        matchLabels:
             app: nginx
   template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
             - name: nginx
               image: nginx:1.9
               ports:
                 - containerPort: 80
