apiVersion: v1
kind: Pod
metadata:
     name: mypod
     namesapce: default
spec:
   containers:
       - name: busybox
         image: busybox
         command:
           - sleep
           - "3600"
