apiVersion: v1
kind: Pod
metadata:
    name: nfs-pv-pod
spec:
    volumes:
      - name: nfs-pv
        persistentVolumeClaim:
           claimName: nfs-pv-claim

    containers:
      - name: nfs-client1
        image: centos:7
        command:
            - sleep
            - "3600"
        volumeMounts:
            - mountPath: "/nfshare"
              name: nfs-pv
    containers:
      - name: nfs-client2
        image: centos:7
        command:
            - sleep
            - "3600"
        volumeMounts:
            - mountPath: "/nfshare"
              name: nfs-pv
